### ISSUE TITLE
Demo gif or video for the README file

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Math-Quiz-Game-In-Cpp#1]
This repository needs a demo gif or video file of the final output.

**Comment by Krishna841** [comment]
Hey!! I want to work on this issue. Can you assign it to me?

**Comment by Susmita-Dey** [comment]
> Hey!! I want to work on this issue. Can you assign it to me?

Sure!!! Go ahead.

**Comment by Krishna841** [comment]
Is this a bug or something?
[image: image.png]

**Comment by Susmita-Dey** [comment]
The image is not visible.

**Comment by Susmita-Dey** [comment]
You've created a PR #5 for this issue. So, I'm closing this PR.
