### ISSUE TITLE
Hey! There's a wrong output in the code for easy level. 

### ISSUE THREAD

**Issue by Krishna841** [Susmita-Dey/Math-Quiz-Game-In-Cpp#3]
Hey! There's a mistake in the code, the answer is not correct.

**Comment by Krishna841** [comment]
Can you assign it to me?

**Comment by Susmita-Dey** [comment]
I've assigned it to you

**Comment by Susmita-Dey** [comment]
You've created a PR #4 FOR THIS ISSUE. So, I'm closing this one.
